spring:
  datasource:
    url: jdbc:mysql://localhost:3307/prod_env
    username: prod_user
    password: prod_password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true